# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7e9572dc62e05ca27ddfb380d124f194"
name = "asd-admin"
handle = "asd-admin"
application_url = "https://asd-assignment.vercel.app/"
embedded = true

[build]
dev_store_url = "storename3122.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://asd-assignment.vercel.app/api/auth/callback" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
