# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0b77a1fb0b2de6c8915e1d2155b34163"
name = "photo-optima"
handle = "photo-optima"
application_url = "https://app.photooptima.com"
embedded = true

[build]
dev_store_url = "photo-optima.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [ "https://app.photooptima.com/api/auth/callback" ]

[webhooks.privacy_compliance]
customer_data_request_url = "https://app1.photooptima.com/webhooks/compliance/customer-request"
customer_deletion_url = "https://app1.photooptima.com/webhooks/compliance/customer-erasure"
shop_deletion_url = "https://app1.photooptima.com/webhooks/compliance/shop-erasure"


[webhooks]
api_version = "2024-04"

[pos]
embedded = true
