name: Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      SHOPIFY_STORE_FRONT_ACCESS_TOKEN: ${{secrets.SHOPIFY_STORE_FRONT_ACCESS_TOKEN}}
      SHOPIFY_STORE_DOMAIN: ${{secrets.SHOPIFY_STORE_DOMAIN}}
      SHOPIFY_ADMIN_ACCESS_TOKEN: ${{secrets.SHOPIFY_ADMIN_ACCESS_TOKEN}}
      NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN: ${{secrets.NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN}}
      NEXT_PUBLIC_SHOPIFY_ADMIN_ACCESS_TOKEN: ${{secrets.NEXT_PUBLIC_SHOPIFY_ADMIN_ACCESS_TOKEN}}
      NEXT_PUBLIC_SHOPIFY_API_KEY: ${{secrets.NEXT_PUBLIC_SHOPIFY_API_KEY}}
      NEXT_PUBLIC_SHOPIFY_API_SECRET: ${{secrets.NEXT_PUBLIC_SHOPIFY_API_SECRET}}
      SHOPIFY_API_KEY: ${{secrets.SHOPIFY_API_KEY}}
      NEXT_PUBLIC_FRONTEND_DOMAIN: ${{secrets.NEXT_PUBLIC_FRONTEND_DOMAIN}}
      NODE_ENV: ${{secrets.NODE_ENV}}
      HOST: ${{secrets.HOST}}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DOMAIN }} 
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: "export NVM_DIR=~/.nvm && source ~/.nvm/nvm.sh && cd /var/www/image-compressor-mq-server && ./.scripts/deploy.sh"