name: photo-optima

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.14.0]
        
    env:
      DATABASE_URL:  ${{secrets.DATABASE_URL}}
      SHOPIFY_STORE_FRONT_ACCESS_TOKEN:  ${{secrets.SHOPIFY_STORE_FRONT_ACCESS_TOKEN}}
      SHOPIFY_STORE_DOMAIN:  ${{secrets.SHOPIFY_STORE_DOMAIN}}
      SHOPIFY_ADMIN_ACCESS_TOKEN:  ${{secrets.SHOPIFY_ADMIN_ACCESS_TOKEN}}
      NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN:  ${{secrets.NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN}}
      NEXT_PUBLIC_SHOPIFY_ADMIN_ACCESS_TOKEN:  ${{secrets.NEXT_PUBLIC_SHOPIFY_ADMIN_ACCESS_TOKEN}}
      NEXT_PUBLIC_SHOPIFY_API_KEY:  ${{secrets.NEXT_PUBLIC_SHOPIFY_API_KEY}}
      NEXT_PUBLIC_SHOPIFY_API_SECRET:  ${{secrets.NEXT_PUBLIC_SHOPIFY_API_SECRET}}
      SHOPIFY_API_KEY:  ${{secrets.SHOPIFY_API_KEY}}
      NEXT_PUBLIC_FRONTEND_DOMAIN:  ${{secrets.NEXT_PUBLIC_FRONTEND_DOMAIN}}
      NODE_ENV:  ${{secrets.NODE_ENV}}
      HOST:  ${{secrets.HOST}}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
